package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"starbucks/graph/model"
)

// PurchaseCoffee is the resolver for the purchaseCoffee field.
func (r *mutationResolver) PurchaseCoffee(ctx context.Context, id string, quantity int) (*model.PurchaseResult, error) {
	r.mutex.Lock()
	defer r.mutex.Unlock()

	coffee, exists := r.coffees[id]
	if !exists {
		return &model.PurchaseResult{
			Success:           false,
			Message:           "Coffee not found",
			RemainingQuantity: 0,
		}, nil
	}

	if coffee.QuantityAvailable < quantity {
		return &model.PurchaseResult{
			Success:           false,
			Message:           fmt.Sprintf("Not enough stock. Only %d available", coffee.QuantityAvailable),
			RemainingQuantity: coffee.QuantityAvailable,
		}, nil
	}

	coffee.QuantityAvailable -= quantity
	return &model.PurchaseResult{
		Success:           true,
		Message:           fmt.Sprintf("Successfully purchased %d %s", quantity, coffee.Name),
		RemainingQuantity: coffee.QuantityAvailable,
	}, nil
}

// Coffees is the resolver for the coffees field.
func (r *queryResolver) Coffees(ctx context.Context) ([]*model.Coffee, error) {
	r.mutex.RLock()
	defer r.mutex.RUnlock()

	coffees := make([]*model.Coffee, 0, len(r.coffees))
	for _, coffee := range r.coffees {
		coffees = append(coffees, coffee)
	}
	return coffees, nil
}

// Coffee is the resolver for the coffee field.
func (r *queryResolver) Coffee(ctx context.Context, id string) (*model.Coffee, error) {
	r.mutex.RLock()
	defer r.mutex.RUnlock()

	coffee, exists := r.coffees[id]
	if !exists {
		return nil, fmt.Errorf("coffee with id %s not found", id)
	}
	return coffee, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
